name: _
publish_to: none

environment:
  sdk: '^3.8.0'

workspace:
  - root_hub_client
  - root_hub_server
  - root_hub_flutter
  - root_hub_flutter_lints
  - root_hub_web_portal

dependency_overrides:
  json_annotation: 4.9.0
  path_provider_foundation: 2.5.1
